// Package genindex regenerates index.md and index/*.md entirely from
// the filesystem scan. These files are canopy-owned artifacts: counts
// are always measured, never incremented, which kills the "+1 drift"
// failure mode of hand-maintained indexes.
package genindex

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/neutrospec/canopy/internal/config"
	"github.com/neutrospec/canopy/internal/wiki"
)

const generatedMark = "<!-- generated by canopy — do not edit by hand; counts are measured from the filesystem -->"

// Regenerate rewrites index.md and index/<category>.md.
func Regenerate(w *config.Wiki, scan *wiki.ScanResult) error {
	today := time.Now().Format("2006-01-02")
	byDir := map[string][]*wiki.Page{}
	for _, p := range scan.Pages {
		byDir[p.Dir] = append(byDir[p.Dir], p)
	}

	indexDir := filepath.Join(w.Root, "index")
	if err := os.MkdirAll(indexDir, 0o755); err != nil {
		return err
	}
	for _, dir := range w.Cfg.Schema.PageDirs {
		if err := writeCategoryIndex(indexDir, dir, byDir[dir], today); err != nil {
			return err
		}
	}
	return writeDashboard(w, scan, byDir, today)
}

func writeCategoryIndex(indexDir, category string, pages []*wiki.Page, today string) error {
	sort.Slice(pages, func(i, j int) bool { return pages[i].Slug < pages[j].Slug })
	var b strings.Builder
	title := strings.ToUpper(category[:1]) + category[1:]
	fmt.Fprintf(&b, `---
title: "%s Index"
created: %s
updated: %s
type: entity
tags: [tool]
sources: []
---

%s

# %s Index

> 모든 %s 페이지 목록.
> **Total**: %d pages

---

`, title, today, today, generatedMark, title, category, len(pages))
	for _, p := range pages {
		fmt.Fprintf(&b, "- [[%s]]\n", p.Slug)
	}
	fmt.Fprintf(&b, "\n---\n*Generated: %s*\n", today)
	return os.WriteFile(filepath.Join(indexDir, category+".md"), []byte(b.String()), 0o644)
}

func writeDashboard(w *config.Wiki, scan *wiki.ScanResult, byDir map[string][]*wiki.Page, today string) error {
	var b strings.Builder
	fmt.Fprintf(&b, `---
title: "Wiki Dashboard"
created: 2026-04-20
updated: %s
type: entity
tags: [tool]
sources: []
---

%s

# Wiki Dashboard

> 개인 지식 베이스 — **검색 중심** 탐색 허브.
>
> **Last updated**: %s | **Total pages**: %d

---

## 📊 Stats by Category

| Category | Count | Last Added | Index |
|----------|-------|------------|-------|
`, today, generatedMark, today, len(scan.Pages))

	archived := countArchived(w)
	for _, dir := range w.Cfg.Schema.PageDirs {
		pages := byDir[dir]
		last := "—"
		for _, p := range pages {
			if p.Created > last || last == "—" {
				last = p.Created
			}
		}
		title := strings.ToUpper(dir[:1]) + dir[1:]
		fmt.Fprintf(&b, "| **%s** | %d | %s | [[index/%s]] |\n", title, len(pages), last, dir)
	}
	fmt.Fprintf(&b, "| **Archived** | %d | — | `_archive/` |\n", archived)

	b.WriteString(`
---

## 🔍 Search

` + "```bash" + `
canopy search "검색어"                  # hybrid (keyword + semantic)
canopy search "검색어" --mode keyword   # fast, no model load
canopy backlinks <page>                 # 역링크
` + "```" + `

**Backend**: canopy 내장 bge-m3 (in-process ONNX, 외부 서버 없음) + SQLite FTS5

---

## 📄 Recent Pages

| Date | Page | Type |
|------|------|------|
`)
	recent := append([]*wiki.Page(nil), scan.Pages...)
	sort.Slice(recent, func(i, j int) bool {
		if recent[i].Updated != recent[j].Updated {
			return recent[i].Updated > recent[j].Updated
		}
		return recent[i].Slug < recent[j].Slug
	})
	for i, p := range recent {
		if i >= 15 {
			break
		}
		fmt.Fprintf(&b, "| %s | [[%s]] | %s |\n", p.Updated, p.Slug, p.Type)
	}
	fmt.Fprintf(&b, "\n---\n*Generated by canopy: %s*\n", today)
	return os.WriteFile(w.IndexMDPath(), []byte(b.String()), 0o644)
}

func countArchived(w *config.Wiki) int {
	n := 0
	filepath.WalkDir(filepath.Join(w.Root, "_archive"), func(path string, d os.DirEntry, err error) error {
		if err == nil && !d.IsDir() && strings.HasSuffix(d.Name(), ".md") {
			n++
		}
		return nil
	})
	return n
}
